### ISSUE TITLE
Wrong link in repo description

### ISSUE THREAD

**Issue by yogeek** [openfaas/templates#10]
Hello,

Not really an issue in the code but the repo introduction sentence contains a link which is leading to a wrong URL :
`Official OpenFaaS templates https://www.openfaas.com/` 
leads to https://github.com/www.openfaas.com instead of https://www.openfaas.com/

Not sure why because source code of the page contains the right href...

**Comment by alexellis** [comment]
Thank you for reporting that!

**Comment by alexellis** [comment]
Fixed this 👍
