### ISSUE TITLE
Table of contents listing templates

### ISSUE THREAD

**Issue by alexellis** [openfaas/templates#100]
Let's create a table of contents listing the template in this repo

| Name  | Language  | Version  | Linux base                 | Watchdog       | Link     |
|--------|-----------|---------|----------------------|--------------|--------|
| `python3` | Python | 3.6 | Alpine Linux 3.8 | Classic |                      | [template/python3](https://github.com/openfaas/templates/tree/master/template/python3) |

**Comment by alexellis** [comment]
Maybe we can link to here too - https://docs.openfaas.com/cli/templates/

**Comment by martindekov** [comment]
Derek assign: me

**Comment by rgee0** [comment]
Did this issue pre-date the template store?  Are we creating maintenance tasks / opportunities to drop the ball?

**Comment by martindekov** [comment]
Hey @rgee0 I think the issue is before we had the template store, but I implemented it with Alex's example. Not sure what you mean by `Are we creating maintenance tasks / opportunities to drop the ball?`

**Comment by alexellis** [comment]
I asked for an index on each template repo so as we add/remove from that GitHub repo we update its documentation. This might be better sparser without the links column so it's easier to maintain. Otherwise I think it's useful if we do this consistently.
