### ISSUE TITLE
mistake in README.MD

### ISSUE THREAD

**Issue by omerzamir** [openfaas/templates#109]
There is a mistake in the Java8 template watchdog type in README.md .

## Expected Behaviour

Correct type of watchdog should be written.
 
## Current Behaviour

Classic watchdog is written instead of [of-watchdog](https://github.com/openfaas-incubator/of-watchdog) in the java8 section.

## Possible Solution

Change classic to of-watchdog in the java8 section.
#110 Is the suggested change.

## Context

README.md is incorrect, I noticed it while pull requesting the java8 template.

**Comment by alexellis** [comment]
That would be great :+1: please go ahead

**Comment by alexellis** [comment]
Cc @martindekov
