### ISSUE TITLE
Add support for ARMv6 devices and build fwatchdog as part of template

### ISSUE THREAD

**Issue by ZeoX06** [openfaas/templates#112]
Add support for ARM 32bit v6 devices like Raspberry Pi Zero.  Also including building of fwatchdog as part of template.

## Expected Behaviour
Add template for ARMv6 devices e.g. python3-armv6
Additional, build fwatchdog as part of template build process

## Current Behaviour
No template available for ARMv6.

## Possible Solution
Working example: 
https://github.com/ZeoX06/templates/blob/arm32v6_support/template/python3-armv6/Dockerfile
I'm not ready with reading the guide to make a pull request ;) 

## Steps to Reproduce (for bugs)
python3-armhf template not running on ARMv6 devices

## Context
Like to use template directly and make it easy for other people to run openfaas on Raspberry Pi Zero devices.

## Your Environment
* Docker version `docker version` (e.g. Docker 17.0.05 ):
18.06.1-ce

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Docker Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux

**Comment by alexellis** [comment]
Hi @ZeoX06 thank you for your interest

OpenFaaS will run on Raspberry Pi Zero but in practice it is not practical and the ecosystem made it a burden for me to maintain on my own.

See more here:

https://github.com/openfaas/faas/issues/501

I'm going to close the issue, but you're welcome to build the code from source - there is nothing I am aware of that should prevent armv6 working.

Alex

**Comment by alexellis** [comment]
Please see my blog on building an ARM cluster here -> https://blog.alexellis.io/build-your-own-bare-metal-arm-cluster/

**Comment by ZeoX06** [comment]
Hi Alex,
next time I will have a better look on the closed issues.
Thanks you for sharing your blog post.

**Comment by alexellis** [comment]
I think you'll find the RPi3 much easier to work with for instance it can run the whole of OpenFaaS on Swarm.

If you'd like to join Slack to chat in our ARM / RPi channel please email alex@openfaas.com
