### ISSUE TITLE
Build error .NET Core

### ISSUE THREAD

**Issue by gdillen** [openfaas/templates#120]
Error "ERROR - Could not execute command: [docker build -t function1:latest .]" when trying to build a .NET Core function.

## Expected Behaviour

N/A
## Steps to Reproduce (for bugs)

1. Create a .NET Core function in a folder  faas-cli new --lang csharp function1
2. cd to the function1 directory
3. Building/deploying the vanilla created function works
4. Open the folder with the Function.csproj + FunctionHandler.cs in vscode
5. Adding Nuget package and change the code
6. Going back to my terminal to the root folder of the created function
7. Run $ faas-cli -action build -f ./function1.yml
8. Result: 
FunctionHandler.cs(15,21): error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create' [/home/app/src/function/Function.csproj]
The command '/bin/sh -c dotnet publish -c release -o published' returned a non-zero code: 1
2019/01/19 20:49:51 ERROR - Could not execute command: [docker build -t function1:latest .]

When trying to build directly in the folder with the csproj and cs file I get:
 Restoring packages for /Users/gdillen/code/openfaas-functions/function1/Function.csproj...
 Generating MSBuild file /Users/gdillen/code/openfaas-functions/function1/obj/Function.csproj.nuget.g.props.
 Generating MSBuild file /Users/gdillen/code/openfaas-functions/function1/obj/Function.csproj.nuget.g.targets.
 Restore completed in 528.53 ms for /Users/gdillen/code/openfaas-functions/function1/Function.csproj.
FunctionHandler.cs(15,21): error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create' [/Users/gdillen/code/openfaas-functions/function1/Function.csproj]

Build FAILED.

FunctionHandler.cs(15,21): error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create' [/Users/gdillen/code/openfaas-functions/function1/Function.csproj]
    0 Warning(s)
    1 Error(s)

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.8.3

* Docker version `docker version` (e.g. Docker 17.0.05 ): 18.09.1

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? Docker Swarm

* Operating System and version (e.g. Linux, Windows, MacOS): MacOS 10.14.2

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
Hi thank you for your interest in OpenFaaS. Please could you create s GitHub repo with your sample and paste the link here?

Currently all the templates undergo Continuous Integration so I don't expect there to be issues with the templates. I'll ask someone to have a look at this but in the meantime would encourage you to check with the docs. 

Alex

**Comment by gdillen** [comment]
Hi, I had functions running before with no problem!
Therefore I started with an out-of-the-box function and made a small change with the result I mentioned.
The GitHub repo with the sample https://github.com/gdillen/openfaas

Thanks.
Guy

**Comment by rorpage** [comment]
I'll be able to take a look at this in 2-3 days unless someone can get to it first.

**Comment by burtonr** [comment]
Hi there @gdillen! Sorry you're having some troubles, but the error you're seeing is related to .NET Core, not specifically OpenFaaS. 

I was able to re-create your issue and saw the cause of the problem. If you try to build your function using the `dotnet` CLI, you will get the same error:

```
$ dotnet build
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restoring packages for /home/burtonr/code/faas/guy/Function.csproj...
  Restore completed in 127.36 ms for /home/burtonr/code/faas/guy/Function.csproj.
FunctionHandler.cs(16,21): error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create' [/home/burtonr/code/faas/guy/Function.csproj]

Build FAILED.

FunctionHandler.cs(16,21): error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create' [/home/burtonr/code/faas/guy/Function.csproj]
    0 Warning(s)
    1 Error(s)
```

A quick search turned up this very brief, but accurate explanation: [missing compiler required member](http://techxposer.com/2018/01/03/missing-compiler-required-member-microsoft-csharp-runtimebinder-csharpargumentinfo-create-solved/)

From inside your function's directory (where the `Function.csproj` file is), run the following command in your terminal:
```
$ dotnet add package Microsoft.CSharp
```

> you could also use VisualStudio and add it as a Nuget package via UI if that's your preference. Just search for the package name in the "Manage Nuget Packages..." view

From there, you should be good to go! I was able to build, and execute your sample function on my machine after adding that additional package.

**Comment by alexellis** [comment]
Thanks both for helping. I also moved this issue from openfaas/faas. I wonder if this is available via API yet for Derek?

Alex

**Comment by gdillen** [comment]
Hi @burtonr indeed now it seems to work.
However, I know I hadn't this issue in the (recent) past (all functions then built without problem). 
Anyway I can proceed with development.
Thanks.

**Comment by burtonr** [comment]
Derek close
