### ISSUE TITLE
Create official Rust template

### ISSUE THREAD

**Issue by bartsmykla** [openfaas/templates#124]
It would be good to have official Rust template

## Expected Behaviour
Having Rust's OpenFaaS template

## Current Behaviour
No Rust template

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by bartsmykla** [comment]
Derek assign: me

**Comment by alexellis** [comment]
I'd like to see one using of-watchdog and the HTTP mode. We already have a good community forking template right?

**Comment by bartsmykla** [comment]
Can do that

**Comment by alexellis** [comment]
Please PR to here when you're ready and after vetting etc we'll get a PR into openfaas/store for the template store. 

https://github.com/openfaas-incubator/rust-http-template
