### ISSUE TITLE
Change the c# examples to string interpolation.

### ISSUE THREAD

**Issue by unglaublicherdude** [openfaas/templates#127]
I know, that these are just examples, but string interpolation is much more readable so I think this change would be a minor improvement to the example in the templates.

The change would be from
```
            return string.Format("Hi there - your input was: {0}\n", input);
```
to
```
            return $"Hi there - your input was: {input}\n";
```

**Comment by unglaublicherdude** [comment]
Pull-Request is merged.

**Comment by alexellis** [comment]
Thank you!
