### ISSUE TITLE
Add dockerfile-arm32v6 template 

### ISSUE THREAD

**Issue by pcorbel** [openfaas/templates#132]
Add a dockerfile arm32v6 template based on the existing dockerfile template

## Expected Behaviour
ARM users should be able to use an official dockerfile template

## Current Behaviour
OpenFaaS don't offer as of now the possibility to run dockerfile functions from an official template on a ARM cluster (like Raspberry pi).

## Possible Solution
Add an official template based on `arm32v6/alpine` instead of `alpine`
`armhf` has been deprecated in favor of `arm32v6`.
Moreover, `arm32v6` is compatible with `arm32v6`, `arm32v7` and `arm64v8` cpus.

## Steps to Reproduce (for bugs)
On an ARM based server, 
1. faas new helloworld --lang dockerfile
2. faas build --yaml helloworld.yml

Container fail to start
 ```docker logs <helloworld container>```
returns
`standard_init_linux.go:190: exec user process caused "exec format error"`

## Context
I was trying to setup an Hello World (dockerfile based) on my Raspberry Pi

## Your Environment
* Docker version `docker version` (e.g. Docker 17.0.05 ):
```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:57:21 2018
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:17:57 2018
  OS/Arch:          linux/arm
  Experimental:     false
```

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? Docker Swarm

* Operating System and version (e.g. Linux, Windows, MacOS): Linux

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Hi @pcorbel,

Thanks for your interest in the project.

armv6 support was removed from OpenFaaS due to lack of demand, compatibility with Kubernetes and limited horse-power to do everything with a very small team of community volunteers.

https://github.com/openfaas/faas/issues/501

If you can use a dockerfile-armhf template then please propose one using the official multi-arch image of `alpine:3.9`.

Alex

**Comment by pcorbel** [comment]
Hi @alexellis,

Understood for the armv6 support.

I can indeed use a  dockerfile-armhf template from either the alpine:3.8 or alpine:3.8 official multi-arch image (thanks you fat manifest...)

The only difference with the current dockerfile template would be the watchdog binary.

Is it okay for you if I open a new issue with the above information or is there still something I'm missing?
