### ISSUE TITLE
Proposal for java8 template changes

### ISSUE THREAD

**Issue by devongleeson** [openfaas/templates#137]
As part of a hack week at my company, I wrote a java8 function that was based on the template provided in this repo. I noticed a few things that could make working with java8 functions a lot easier. I'd be willing to do the work, but I want to make sure it is wanted before I go off and invest in doing the work.

## Expected Behaviour
Development of java functions should be more flexible and integrate with IDEs well. 

## Current Behaviour
* Locally developed code might end up getting compiled at a different source compatibility level.
 * Intellij doesn't understand how to find the handler interfaces, so it thinks the code is broken by default.
* The entry point `App` is hard coded to point at `com.openfaas.function.Handler`.

## Possible Solution
* Set the following in build.gradle: `sourceCompatibility = 1.8`, `targetCompatibility = 1.8` 
* Publish the handler interface jar to maven-central or jCenter.
* The app should be configurable, so that the function can be, for example `com.tripwire.faas.MyHandler`, which would make it easier to have reuse of code. I propose that the App look for configuration and reflectively call the function handler it is configured to call, and default to `com.openfaas.function.Handler`.

## Context
I found developing a java8 function to be cumbersome, and ended up "vendoring" the interfaces into my code. The better solution would be to publish the interfaces jar to jCenter so that my code can depend on it there. 

I use the JDK 11, and while I was developing on this, I ran into issues with source comparability. Adding the source comparability flags are a simple fix to make it so this doesn't happen to other people.

I found the way that the handler is hard coded to the openfaas package to be inconsistent with the way that other serverless frameworks work. For example, with aws lambda I can have multiple functions in the same "function bundle" and then point aws lambda at different functions within the bundle by specifying "com.mycompany.code.Function" at deploy time. This enables more code reuse.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

Docker version 18.09.2

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):

Linux

* Link to your project or a code example to reproduce issue:

The code I worked on is proprietary at this time.

**Comment by alexellis** [comment]
Thanks for your interest.

You should also take a look at https://github.com/openfaas/store/issues/70

**Comment by devongleeson** [comment]
I think the only part of my plan that would require coordination is the publishing the interfaces jar part. I think I could tee most of it up, but it would require some additional steps with bintray. It requires an account, which is free for open source, but I probably shouldn't be the one that opens the account/owns it. I can hook the publishing bits up to travis, but someone will need to store the bintray secretes in travis for me.

**Comment by anmtan** [comment]
It would be great to see this is improved. I am using Java8 template. Intellij thinks the code is broken after import.

**Comment by alexellis** [comment]
This will be happening shortly. Feel free to join Slack to keep in touch. 

--
Join Slack to connect with the community
https://docs.openfaas.com

**Comment by psoares** [comment]
I fixed the issue of intelliJ not recognizing the interfaces by setting the following in the settings.gradle of my function:
```
rootProject.name = 'function'
include ':model'
project(":model").projectDir = new File(settingsDir, '../template/java8/model')
```

**Comment by alexellis** [comment]
Thank you @psoares that's great.

I have registered an account with jCenter, it's on my list to publish the packages there instead of shipping them in the template. I'll need some help with that or to carve out some hours to get up to speed one day over the summer.

**Comment by tim-hellhake** [comment]
@alexellis How can I help?

**Comment by alexellis** [comment]
@psoares @tim-hellhake let's move over discussion to https://github.com/openfaas/templates/issues/181 ?

**Comment by alexellis** [comment]
@devongleeson contributions are welcome to the Java template(s)

**Comment by alexellis** [comment]
Closed by: https://github.com/openfaas/templates/issues/210
