### ISSUE TITLE
Get Maven central co-ordinates to publish dependency jars

### ISSUE THREAD

**Issue by kameshchauhan** [openfaas/templates#140]
@alexellis 
As part of resolution of issue https://github.com/openfaas/store/issues/70, there is a need to get access/coordinates on Maven Central Nexus Repository to host/publish the dependency jar files.

Create an account and raise ticket at: https://issues.sonatype.org/login.jsp

Refer the sample issue i have created for the same: https://issues.sonatype.org/browse/OSSRH-47615

Read this article for more details: https://central.sonatype.org/pages/ossrh-guide.html

## Expected Behaviour
The dependency jar project should be able to publish the artifacts on Maven Central 

## Current Behaviour
Currently few dependencies are provided as source code and should be changed to improve developer experience. 

## Possible Solution
Follow the link to request Nexus coordinate as "com.openfaas.*" in general for OpenFaaS organization. For the specific issue#70, the co-ordinates will be "com.openfaas.template.java".

**Comment by alexellis** [comment]
@kameshchauhan https://issues.sonatype.org/browse/OSSRH-48617

**Comment by alexellis** [comment]
Derek close: resolved
