### ISSUE TITLE
Why Java function so complicated？

### ISSUE THREAD

**Issue by fstonezst** [openfaas/templates#144]
I notice that the implement of function in other language has a very sample templete style, So  why java is so  complicated?

**Comment by alexellis** [comment]
Hi thanks for your interest in the project.

The handler for Java is particularly simple IMHO.

Can try to be more specific and constructive?

**Comment by alexellis** [comment]
@fstonezst

**Comment by fstonezst** [comment]
I just want to ask about the principle of openfaas, not a suggest or a demand.  It's only two code file in the go template (main.go&handler.go ). But there are so many code file in the java template. So why the faas of java needs so many work? Thank you for your attention.
