### ISSUE TITLE
Java 11 & 12 template

### ISSUE THREAD

**Issue by nwong4932** [openfaas/templates#146]
Can't create function with Java 11 or Java 12
## Expected Behaviour

a Java 11 or Java 12 template provided
## Current Behaviour

only Java 8 template available
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Hi is that some specific feature that you need from Java 11 or 12?

What I would suggest you do is look at the java 8 template, fork it into your own repo and then update the dockerfile. 

Let me know how you get on with that and if you need any help please feel free to ask on Slack. 

Alex

**Comment by alexellis** [comment]
@nwong4932 ... it's August now and I've still not heard back from you. Can you report back please?

Alex
