### ISSUE TITLE
Missing Gradle Wrapper script files from java8 template

### ISSUE THREAD

**Issue by agasser** [openfaas/templates#153]
The java8 template is missing Gradle Wrapper scripts

## Expected Behaviour
After using the java8 template to create a function, the Gradle wrapper can be used to build the project with `gradlew.bat` on windows or `./gradlew` on Unix.

## Current Behaviour
The required script files are missing. See `gradlew` and `gradlew.bat` in the [Gradle Wrapper documentation](https://docs.gradle.org/current/userguide/gradle_wrapper.html)

## Possible Solution
Add the missing files

**Comment by alexellis** [comment]
Thank you for raising this issue. I think the concern I had was committing binary files for each function. 

What does the file size structure look like with these files added back?

**Comment by alexellis** [comment]
--
Join Slack to connect with the community
https://docs.openfaas.com

**Comment by agasser** [comment]
The binary file (gradle.jar) is already there. It is just the wrapper scripts that are missing.

**Comment by alexellis** [comment]
Would you like to submit a PR so we can see what it looks like on a diff?

**Comment by agasser** [comment]
Looks like this was fixed by https://github.com/openfaas/templates-sdk/pull/3
