### ISSUE TITLE
copy go source code into image is unnecessary

### ISSUE THREAD

**Issue by chennqqi** [openfaas/templates#157]
https://github.com/openfaas/templates/blob/f498818af1ec771d2b11388ad2c74f8b011addf0/template/go/Dockerfile#L33

**Comment by alexellis** [comment]
Hi @chennqqi the copy statement is not in order to ship the source-code, but to ship any artefacts and static files which the user wishes to add.

If you have an alternative in mind, then please do feel free to propose it. I'll close the issue until we have a better option. 

Alex
