### ISSUE TITLE
JDK in java8 template is very old

### ISSUE THREAD

**Issue by tim-hellhake** [openfaas/templates#163]
## Expected Behaviour

Java8 template uses the latest JDK8 version.

## Current Behaviour

Java8 template uses JDK 8u131 which is more than two years old.

## Possible Solution

Use the latest tag of the jdk8 image.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

The used jdk misses several security updates.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
18.09.2

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Hi @tim-hellhake 

Please fill out the whole issue template. I've already mentioned this on #166 

Alex

**Comment by alexellis** [comment]
Related: https://github.com/docker-library/openjdk/issues/345

**Comment by tim-hellhake** [comment]
I did some research based on the linked issues.

The last release of openjdk8 in alpine was u212.
https://pkgs.alpinelinux.org/package/edge/community/x86/openjdk8

As the openjdk8 alpine image is built from the openjdk8 package in the alpine repository the latest image version is also u212.

Azule puts a lot of effort into releasing tck tested openjdk [builds](https://www.azul.com/downloads/zulu-community/) for various os and architectures.
They also provide the latest openjdk8 builds as [alpine](https://hub.docker.com/r/azul/zulu-openjdk-alpine) images.

Corretto also provides the latest jdk8 images however there are no alpine based variants.
There is an open [issue](https://github.com/corretto/corretto-8-docker/issues/1) for alpine support though.

Updating the jdk8 version to u212 (April 2019) would improve the situation significantly however it's no a long term solution.
Does something speak against using the azul image?
