### ISSUE TITLE
Update gradle to the latest release

### ISSUE THREAD

**Issue by tim-hellhake** [openfaas/templates#165]
## Expected Behaviour

The latest gradle version is used (5.1.1).

## Current Behaviour

The used gradle version is 4.8.1.

## Possible Solution

Update the gradle version in the Dockerfile and the property files for the gradle wrappers.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Gradle version is outdated.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
18.09.2

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Hi @tim-hellhake 

Thank you for your interest in the project.

Please fill out the whole issue template, this is not optional.

https://github.com/openfaas/templates/blob/master/.github/ISSUE_TEMPLATE.md

Alex

**Comment by alexellis** [comment]
Derek close: fixed, latest is now live.
