### ISSUE TITLE
Python2 is out of support

### ISSUE THREAD

**Issue by Waterdrips** [openfaas/templates#188]
Python2 has reached EOL, 

Is there a process for retiring a template? 
Also any examples with the python2 template probably want porting to python3 templates.

**Comment by alexellis** [comment]
What is AWS doing for this? I heard they are extending support for several years, do they publish a docker image we can use? For instance - remember what they did with Java and Corretto? https://aws.amazon.com/corretto/

**Comment by alexellis** [comment]
I think we've already discouraged usage and given a warning in the custom_message in the template and the workshop/homepage also uses only Python3 as far as I remember.

**Comment by alexellis** [comment]
OK, we don't have a welcome_message or such in the "python" template, @Waterdrips feel free to add one. See node or go as examples.

This and the workshop seem like the most important areas to cover, and we have done:

![note](https://user-images.githubusercontent.com/6358735/73077621-6ce3e280-3eb8-11ea-91bb-79098bf11aa6.png)

https://docs.openfaas.com/cli/templates/#python-3-classic-template
