### ISSUE TITLE
node12 template cannot access chunked requests

### ISSUE THREAD

**Issue by burtonr** [openfaas/templates#199]
This came up in Slack via @nachiket-p 

The node12 template does not make available the request when received as `transfer-encoding: chunked`

## Expected Behaviour

Chunked requests should be able to be utilized in the node12 template

## Current Behaviour

Currently, the event object is effectively empty making it impossible to access the request

## Possible Solution

Possibly need to add a property to the `FunctionEvent` that would contain the full request so that the function can then listen to events on the request? 

Not sure. This would need a bit of R&D to be done

## Steps to Reproduce (for bugs)

1. Create a new node12 function: `faas-cli new chunker --lang node12`
2. Set the `RAW_BODY` env var in the `yml`
``` yaml
version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  chunker:
    lang: node12
    handler: ./chunker
    image: chunker:latest
    environment:
      RAW_BODY: true
```

3. Deploy the function: `faas-cli deploy -f chunker.yml`
4. cURL with the `transfer-encoding` header set to `chunked`:
```sh
curl -H "transfer-encoding:chunked" http://127.0.0.1:8080/function/chunker -T chunker.yml
```
5. Observer the function logs and output:
> I've added `console.log('Event object: ', event);` to the handler to see everything
```sh
chunker.1.k0tn2b437mgp@pop-os    | 2020/02/20 03:48:29 stdout: RAW_BODY env var value:  true
chunker.1.k0tn2b437mgp@pop-os    | 2020/02/20 03:48:29 stdout: Event object:  FunctionEvent {
chunker.1.k0tn2b437mgp@pop-os    | 2020/02/20 03:48:29 stdout:   body: {},
chunker.1.k0tn2b437mgp@pop-os    | 2020/02/20 03:48:29 stdout:   headers: {
chunker.1.k0tn2b437mgp@pop-os    | 2020/02/20 03:48:29 stdout:     host: 'chunker:8080',
chunker.1.k0tn2b437mgp@pop-os    | 2020/02/20 03:48:29 stdout:     'user-agent': 'curl/7.65.3',
chunker.1.k0tn2b437mgp@pop-os    | 2020/02/20 03:48:29 stdout:     'transfer-encoding': 'chunked',
chunker.1.k0tn2b437mgp@pop-os    | 2020/02/20 03:48:29 stdout:     accept: '*/*',
chunker.1.k0tn2b437mgp@pop-os    | 2020/02/20 03:48:29 stdout:     'accept-encoding': 'gzip',
chunker.1.k0tn2b437mgp@pop-os    | 2020/02/20 03:48:29 stdout:     expect: '100-continue',
chunker.1.k0tn2b437mgp@pop-os    | 2020/02/20 03:48:29 stdout:     'x-call-id': '32872703-4e6c-41d2-9f84-198d76e458c9',
chunker.1.k0tn2b437mgp@pop-os    | 2020/02/20 03:48:29 stdout:     'x-forwarded-for': '10.255.0.2:37500',
chunker.1.k0tn2b437mgp@pop-os    | 2020/02/20 03:48:29 stdout:     'x-forwarded-host': '127.0.0.1:8080',
chunker.1.k0tn2b437mgp@pop-os    | 2020/02/20 03:48:29 stdout:     'x-start-time': '1582170509610013546'
chunker.1.k0tn2b437mgp@pop-os    | 2020/02/20 03:48:29 stdout:   },
chunker.1.k0tn2b437mgp@pop-os    | 2020/02/20 03:48:29 stdout:   method: 'PUT',
chunker.1.k0tn2b437mgp@pop-os    | 2020/02/20 03:48:29 stdout:   query: {},
chunker.1.k0tn2b437mgp@pop-os    | 2020/02/20 03:48:29 stdout:   path: '/'
chunker.1.k0tn2b437mgp@pop-os    | 2020/02/20 03:48:29 stdout: }
chunker.1.k0tn2b437mgp@pop-os    | 2020/02/20 03:48:29 PUT / - 200 OK - ContentLength: 31

```

The output (with `-vvv` on cURL):
```sh
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> PUT /function/chunker HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.65.3
> Accept: */*
> transfer-encoding:chunked
> Expect: 100-continue
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 100 Continue
* Signaling end of chunked upload via terminating chunk.
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Connection: keep-alive
< Content-Length: 31
< Content-Type: text/html; charset=utf-8
< Date: Thu, 20 Feb 2020 03:48:29 GMT
< Etag: W/"1f-Oew2PbzCQVOoh/DOlPq3Fcx/m/k"
< X-Call-Id: 32872703-4e6c-41d2-9f84-198d76e458c9
< X-Duration-Seconds: 0.006663
< X-Start-Time: 1582170509610013546
< 
* Connection #0 to host 127.0.0.1 left intact
{"status":"Received input: {}"}
```

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
19.03.2
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Swarm locally only to reproduce the issue
* Operating System and version (e.g. Linux, Windows, MacOS):
Linux
* Link to your project or a code example to reproduce issue:
N/A

**Comment by burtonr** [comment]
I did find this (somewhat related) issue in express/body-parser: https://github.com/expressjs/body-parser/issues/191

I also reviewed the video streaming functions here: https://github.com/cconger/openfaas-streaming-demos but found those are all bash functions, so not much help.

Finally, I found this gist example of uploading a chunked request to an express server here: https://gist.github.com/PaulMougel/7511372 possibly for inspiration

Not sure if that's of any help, just wanted to share my research so far.

**Comment by alexellis** [comment]
Looks like the raw parser appears to reject requests without a content-length header, i.e. chunked encoding. The PHP Swoole server had a similar issue and I added a configuration to the watchdog to buffer the data. 

It should work here too - https://github.com/alexellis/php7-swoole-template/blob/master/template/php7-swoole/Dockerfile#L17

**Comment by dnechay** [comment]
@alexellis faced the same issue when tried to use [sqs connector](https://github.com/openfaas-incubator/openfaas-sqs-connector) for my function.
Under the hood node12 template uses `body-parser`. If there is no `content-type` header in a request then the body is empty.
sqs connector doesn't set this header when sends sqs message to function, but should set to `text/plain`.

@burtonr so seeing on my issue I guess you have to specify correct `content-type` header and use `RAW_BODY: true`

**Comment by alexellis** [comment]
Correct - use the RAW_BODY option. If you need some other options then feel free to suggest them.
