### ISSUE TITLE
Is there a way to read a file sent to a function via a POST request?

### ISSUE THREAD

**Issue by AldiT** [openfaas/templates#200]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

I am trying to send a file to the function and further process it inside this function. The problem is that when a file is sent to the function, it is located at the "req" argument to the function. Now this is accessible inside the function, but I don't know any parser capable of parsing the bytes in the argument and extracting the image. I searched for a tutorial or example that does smth similar, but all including the ones used to process an image use external IP to access the image in this case. Is there a parser or a simple way to extract the file bytes from the req string? Or is this simply not possible till now?

## Possible Solution

There could a be a parser I don't know about that extracts data from this byte string, or there is a faas built in way to receive files from the request to the function.

## Steps to Reproduce (for bugs)

1. Create a simple function and deploy it, return the req.
2. Send an image using a Postman (or other tool)
3. View the request content

## Context

As I said above I am trying to process a file the user uploads to the function (e.g. an image)

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):commit:  ea687659ecf14931a29be46c4d2866899d36c282
 version: 0.11.8

* Docker version `docker version` (e.g. Docker 17.0.05 ): 19.03.2

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? OpenShift(faas-netes, Kubernetes)

* Operating System and version (e.g. Linux, Windows, MacOS): Windows 10

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by AldiT** [comment]
Hi , thanks for your response!

I am using python3 as a template. 

I have seen the docs, but this far, I have seen no example to what I am trying to do.

Unfortunately, I cannot point you to the code because it is on a private hub, but it is nothing special, I just try to parse the below string using various parsers(cgi, parse_qs python) , but to make the picture more clear I will add some info here:

```
b'----------------------------327752973836863047150009\r\nContent-Disposition: form-data; name="name"\r\n\r\naldi from
body\r\n----------------------------327752973836863047150009
```

This would be the body of a request sent to the function (req argument), if it is a file the bytes of the file would be where my name currently is(with the corresponding tag names). On your labs on the git repo the images processed by functions are downloaded using "requests", in case of python, to the function. What I want to do is, to not get a url to an image, but instead get the image itself in the function. The most similar thing I can think of would be the way a file is uploaded to Flask:

`file = request.files['filename']`

In faas case request is the req parameter which looks as the string posted above.

If you neccessarily need a repo I can create one for you in my account and point you to it.

**Comment by AldiT** [comment]
Hey @alexellis , I hope this thread is still under your attention. 
For some more information I have an example of what I want to do here: https://github.com/AldiT/multipart_template/blob/master/flask_example.py

If I can draw an analogy to this, a good one in my opinion would be the use of aws lambda + API Gateway from aws to handle form data (multipart/form-data). Is this supported from OpenFaaS (to the best of my knowledge it is not)? Do you recommend a specific parser to parse the req as shown above? Or is there another "official" work-around?

**Comment by alexellis** [comment]
You should be able to do this with the flask template we provide in the store. Please feel free to use Slack for technical support.
