### ISSUE TITLE
[Question] Python Templates - Why two requirements.txt?

### ISSUE THREAD

**Issue by Kryan90** [openfaas/templates#208]
Sorry if this isn't the right forum for this question, but I couldn't find anywhere else for general questions related to templates.

I am curious as to why all the python templates define a requirements.txt at the same level as the Dockerfile and then an additional requirements.txt in the function directory.

Can anyone provide context on what sort of design pattern this is supposed to enable? I can see how it might be useful if you are building out multiple functions and want to have a single Dockerfile that builds images for each one, but there isn't any built in handling for that in the templates.

What would be the ideal use-case here?

**Comment by alexellis** [comment]
No worries, you can ask about this on the OpenFaaS Slack.
