### ISSUE TITLE
Publish java11 model packages to Maven Central

### ISSUE THREAD

**Issue by alexellis** [openfaas/templates#210]
## Description

Publish java11 model packages to Maven Central

Given complaints from Java users, we should provide a remote JAR that they can download for the model package, rather than bundling it into their local build.

This enables intelli-sense and removes any "unknown package" errors from IDEs.

I'll close the related issues:

https://github.com/openfaas/templates/issues/181
https://github.com/openfaas/templates/issues/137

A claim has been put in with Maven Central here using their JIRA ticket system -> https://issues.sonatype.org/browse/OSSRH-59387

**Comment by alexellis** [comment]
It seems that my previous request may have been approved as it's set to fixed -> https://issues.sonatype.org/browse/OSSRH-48617

**Comment by ieugen** [comment]
They where published with a different group id and artifact id. 
See the comments. 

The build + tests and checks could be automated with some CI and also the release process.  
Is there infrastructure in place for this ?

**Comment by alexellis** [comment]
Let's take baby steps, and learn the publishing process (which is very complicated TBH) before running and tripping over our own feet.

https://central.sonatype.org/pages/gradle.html

Latest status: unable to release artifact - https://issues.sonatype.org/browse/OSSRH-59394

**Comment by alexellis** [comment]
All work completed in https://github.com/openfaas/templates/pull/214 and https://github.com/openfaas/templates-sdk
