### ISSUE TITLE
Check all usages of root in templates

### ISSUE THREAD

**Issue by alexellis** [openfaas/templates#23]
## Description

All templates in this repository should be using non-root users

This is the case for Go and some of the other templates, but we need to review all other templates including ARM to make sure they are covered by this work and it is fully tested.

The easiest way to do this task is to look into each Dockerfile and make sure there is a `USER` statement pointing to a non-root user.

## Acceptance

Any changes need testing including testing with adding modules - i.e. `pip` for python, `nuget` packages for C#

**Comment by BurtonR** [comment]
I've found that the only templates that _do_ have a non-root user are:
* go-armhf
* go
* node

I can update these in the next day or two, unless someone else wants to jump in.

One question for you though @alexellis: In the Node template's Dockerfile, there's a note
`# chmod for tmp is for a buildkit issue (@alexellis)`
Is this needed for all the templates, or is that just a special case for Node? I see the `tmp` directory is not modified in the Go template. Also, where and how did you spot that issue so I can be sure that when I update these, the same issue doesn't come up.

**Comment by iyovcheva** [comment]
@BurtonR I can work on this if you're fine with that and didn't have a chance to start?

**Comment by alexellis** [comment]
@iyovcheva please validate the analysis - we're looking for what the final state is of the image - i.e. root or some other user.

**Comment by iyovcheva** [comment]
I verified that `go-armhf`, `go` and `node` templates use non-root users. 
Updating the PR with the templates one by one.

**Comment by BurtonR** [comment]
Thanks @iyovcheva!
