### ISSUE TITLE
node12: add limit environment variable for raw (application/octet-stream)

### ISSUE THREAD

**Issue by fundef1** [openfaas/templates#245]
I can't seem to set the limit for bodyParser.raw - i.e. when using a Content-Type: application/octet-stream

## Expected Behaviour
i was expecting an equivalent to the MAX_JSON_SIZE environment variable. 
I'm not a (js) programmer, but I couldn't find a clean way to set the limit for the raw parser.

## Current Behaviour
bodyParser.raw defaults to 100kb

## Possible Solution
I hacked the node12 template locally and simply added a MAX_RAW_SIZE, but there's probably a cleaner way.
```
    var jsonLimit = process.env.MAX_JSON_SIZE || '100kb' //body-parser default
    var rawLimit = process.env.MAX_RAW_SIZE || '100kb' //body-parser default
    app.use(bodyParser.json({ limit: jsonLimit}));
    app.use(bodyParser.raw({ limit: rawLimit})); // "Content-Type: application/octet-stream"
    app.use(bodyParser.text({ type : "text/*" }));
```

a generic MAX_SIZE might be cleaner though.

**Comment by alexellis** [comment]
How about this?

https://github.com/openfaas/templates/blob/master/template/node12/index.js#L15
