### ISSUE TITLE
Execution timeout greater than 2 minutes is not honored by `node12` template

### ISSUE THREAD

**Issue by ggrussenmeyer** [openfaas/templates#252]
When invoking over HTTP a `node12` function whose`exec_timeout` is greater than 2 minutes, an empty response with a 500 status code is received after 2 minutes have elapsed.

## Expected Behaviour
When invoking over HTTP a long-running `node12` function for which `exec_timeout` is greater than 2 minutes (and assuming timeouts values are adequately configured on infrastructure components such as gateway, controller, etc.), no response is received until either the function finishes (hence with a status code as specified by the function code) or the `exec_timeout` duration is reached (hence with a 504 status code, as set by the gateway).

## Current Behaviour
When invoking over HTTP a long-running `node12` function for which `exec_timeout` is greater than 2 minutes (and assuming timeouts values are adequately configured on infrastructure components such as gateway, controller, etc.), the response is received after 2 minutes, with a 500 status code and an empty body.
The following message is logged at function level: 
```log
2021/04/01 11:31:09 Upstream HTTP request error: Post "http://127.0.0.1:3000/": EOF
```
The following message is logged at gateway level:
```log
2021/04/01 11:31:09 Forwarded [POST] to /function/long-running-function - [500] - 120.086259s seconds
```

Note: although a response is received, the request continues to be processed server side (i.e. the function does not get interrupted), but of course the resulting response will never reach the client. 

## Root cause
Node.js functions are exposed using Express, which in turn uses the Node.js "native" HTTP server, which is by default configured to timeout after 120 seconds (cf. https://nodejs.org/dist/latest-v12.x/docs/api/http.html#http_server_timeout).

As this timeout value is not set by the template code to match the function `exec_timeout` duration, any request taking more than this default value will be considered as timing out by the Node.js runtime, which will close the response before the function can complete, whatever `exec_timeout` duration is specified in the function's descriptor.

## Possible Solution
From my perspective, the template code should take whatever action required to ensure the function may respond for at most the specified `exec_timeout` duration.
As such, it could either:
* set once the server timeout to match `exec_timeout`;
* or set the response timeout to match `exec_timeout` on each request.

As a workaround, the default duration for the HTTP server timeout can be specified using the `--http-server-default-timeout` command line argument of the `node` binary.
For example:
```yaml
environment:  
  fprocess: "node --http-server-default-timeout=240000 index.js"
```
This workaround seems suboptimal to me because it requires overloading the `fprocess` environment variable in the function descriptor, leading to duplication because the execution timeout then appear twice in the function descriptor (once as `exec_timeout` for the watchdog process and once in the `fprocess` environment variable).

## Steps to Reproduce (for bugs)
1. Build, push and deploy a function that will take more than 120s to complete.
2. Invoke that function over HTTP (using a standalone client -`curl` or the like- or using the UI)
3. Observe that response is received after 120s, with a 500 status code and an empty body, instead of the expected status code and body.

## Context
Trying to execute a Node.js data processing function that can take more than 3 minutes to complete.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Does not seem relevant.

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?  
Kubernetes.

* Operating System and version (e.g. Linux, Windows, MacOS):
Does not seem relevant.

* Link to your project or a code example to reproduce issue:
Not available yet.

**Comment by alexellis** [comment]
The change you propose here looks reasonable: https://github.com/ggrussenmeyer/openfaas-templates/commit/20253e88d398ab75446d83b68fe075b1b5dd1938

Would you like to raise a PR and show some end to end testing that you've done? Or provide a sample repo that we can deploy to see this in action?

Alex

**Comment by ggrussenmeyer** [comment]
Hi @alexellis,

yes definitely, I was about to raise a PR but realized it did miss some more end to end testing than our internal usage provides, I'm working on it (with a sample repo).

I also have a philosophical issue regarding the possible race condition between the Node.js side timing out versus the watchdog timing out: given that Node.js timing out abruptly closes the response stream and triggers a 500 error, wouldn't it be safer to have the Node.js timeout set to something a little bit greater than the function's timeouts so that it is guaranteed that the watchdog always kicks in first (thus avoiding responding w/ 500 errors to clients)?
Or am I over-engineering here?

**Comment by kevin-lindsay-1** [comment]
I have my own template for node, and I recall running into this way back, but I was still getting used to OF so it didn't cross my mind to create a ticket. I ended up parsing the duration to match what you can pass in to openfaas (as in, go-style duration), converting that to milliseconds, and then setting the timeout in express to match.

**Comment by alexellis** [comment]
@ggrussenmeyer thanks for the WIP branch you have in your fork. Could you send us a PR please? I've also left you a couple of comments.

**Comment by alexellis** [comment]
Closing since in node14 there is no default timeout, so it's unbounded and will be detected by the watchdog.

Users wishing to go beyond 2m should use node12.

Alex
