### ISSUE TITLE
Does not support springboot templates

### ISSUE THREAD

**Issue by vampireslove** [openfaas/templates#263]
I want to use springboot to develop serverless functions with openfaas，but  Does not support springboot templates。

**Comment by alexellis** [comment]
Hi,

There's nothing stopping you from creating your own Springboot template or using a simple Dockerfile approach. If you would like consulting or professional services, feel free to reach out via https://openfaas.com/support/

We also need everyone to fill out the issue template, could you do that please?

https://raw.githubusercontent.com/openfaas/templates/master/.github/ISSUE_TEMPLATE.md

Alex
