### ISSUE TITLE
node v12: Error: listen EADDRINUSE: address already in use

### ISSUE THREAD

**Issue by rvarkonyi** [openfaas/templates#272]
Trying to run a simple app in a Digital Ocean kubernetes cluster using the node v12 template but getting this error when invoking the function:

`Error: listen EADDRINUSE: address already in use :::3000`

I've definitely not got anything running on this port (tried to use other arbitrary ports, always getting the same error).

Any help would be appreciated.

Thanks

## Your Environment
Kubernetes running on Digital Ocean

* What version of Kubernetes are you using? `kubectl version v1.21.5`

**Comment by LucasRoesler** [comment]
Hi @rvarkonyi without some more details I don't know if we can really help debug this. Can you include more information about your app and any other software you installed in your cluster, including how you installed openfaas? Ideally, if you can share a link to your app code and give concrete instructions for the comands you ran on your cluster, that will allow us to attempt to help.

**Comment by alexellis** [comment]
Reviewed on the Office Hours call today, no response from original poster, so closing.

If someone else runs into this, please raise your own issue.
