### ISSUE TITLE
[Typo] Node template naming in README is wrong

### ISSUE THREAD

**Issue by cactysman** [openfaas/templates#277]
Hey there, 081622a added new Node.js templates to the README document, but they're are all named `node14` instead of `node16` and `node17`,

See:
https://github.com/openfaas/templates/blob/d8893afe3d1072840174911859c6f5db2986e814/README.md?plain=1#L19-L20

I was about to create a pull request, but the contributing guide [told me not to](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md#ive-found-a-typo), so here's the issue. 😃

**Comment by LucasRoesler** [comment]
@cactysman feel free to send the PR
