### ISSUE TITLE
Python template fails - "standard_init_linux.go:195: exec user process caused 'exec format error'"

### ISSUE THREAD

**Issue by bdparrish** [openfaas/templates#3]
Function successfully built, pushed, and deployed.

The pod status ends with "CrashLoopBackOff".

**Steps**

1. `faas-cli new --lang python-armhf hello-python`
2. `faas-cli build -f ./hello-python.yml`
3. `faas-cli push -f ./hello-python.yml`
4. `faas-cli deploy -f ./hello-python.yml`

<img width="1160" alt="screen shot 2018-01-01 at 10 31 55 am" src="https://user-images.githubusercontent.com/720788/34468822-0b88edee-eedf-11e7-90b8-4b58908bcb1f.png">

<img width="1176" alt="screen shot 2018-01-01 at 10 32 33 am" src="https://user-images.githubusercontent.com/720788/34468824-1d0003d2-eedf-11e7-9eb7-322186725235.png">

**Comment by alexellis** [comment]
Can you raise this issue over on the `faas-cli` repo. What platform is this? You really have to provide more details than this if you need support.. thanks.. Alex

**Comment by alexellis** [comment]
Unable to reproduce the error. Have moved the issue over to: https://github.com/openfaas/faas-cli/issues/273

**Comment by alphara** [comment]
I got the the same `exec format error` with node14, node16, node17 images.

**Comment by LucasRoesler** [comment]
Hi @alphara  this is a pretty old ticket, if you are having this issue can you please open a new issue with the reproduction details for your situation and add back reference to this issue.  

Most likely there is a issue with how the image is being built , this  error `"standard_init_linux.go:195: exec user process caused 'exec format error'"` usually means that you are trying to run an image built for `amd` (ie intel etc) on a node that is using an `arm` based chip (e.g. a Raspberry Pi), or vice versa.

**Comment by alphara** [comment]
Hi @LucasRoesler. Thank you for the message. Yes, I found that I was building the images on Apple M1 chip (ARM) but running on the AMD architecture. I rebuilt the image on a machine with the same type of the architecture and it works.
