### ISSUE TITLE
Update node17 template (and prior, if you have time) to use chown from Docker

### ISSUE THREAD

**Issue by alexellis** [openfaas/templates#300]
Update node17 template (and prior, if you have time) to use chown from Docker

## Expected Behaviour

Where possible, when copying files between stages or from the build context, use Docker's own chown command.

## Current Behaviour

Not used

## Steps to Reproduce (for bugs)

1. Create a new function and install something big and slow like the AWS SDK
2. Try faas-cli build and see how it goes?
3. After, I hope it should be quicker

Example of a large function to build

https://github.com/alexellis/gumroad-custom-workflow

**Comment by NikhilSharmaWe** [comment]
@alexellis I think this issue is resolved now.
We can close this issue now.

**Comment by alexellis** [comment]
Remind me why?
