### ISSUE TITLE
Different support for concurrent execution?

### ISSUE THREAD

**Issue by wiluen** [openfaas/templates#307]
I conducted performance testing on different functions and found that some functions can execute requests concurrently within in a single function container(e.g., pythton), while others can only execute requests in sequence.(e.g., Golang,node) I would like to know the reason and what factors determine this issue?
## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] No

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* What Docker version are you using? `docker version`

* What version of Kubernetes are you using? `kubectl version`
K8S1.23
* Operating System and version (e.g. Linux, Windows, MacOS):
LINUX
* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Hi there,

> I conducted performance testing on different functions and found that some functions can execute requests concurrently within in a single function container(e.g., pythton), while others can only execute requests in sequence.(e.g., Golang,node)

That's simply not the case.

All templates support concurrency and parallel invocations.

You'll need to provide your testing method and results, with reproducible samples if you'd like us to comment further.

Alex
