### ISSUE TITLE
Missing use ADDITIONALPACKAGE on GoLang template

### ISSUE THREAD

**Issue by raniellyferreira** [openfaas/templates#309]
I noticed that the GoLang template in the OpenFaaS templates repository is missing the use of ADDITIONALPACKAGE in the Dockerfile. This can be seen at line 42 in the Dockerfile:

```Dockerfile
RUN apk --no-cache add ca-certificates ${ADDITIONAL_PACKAGE}
```

The ADDITIONAL_PACKAGE variable allows users to specify additional packages to be installed in the Docker image. It would be helpful to include this line in the template so that users can easily add extra packages when building their functions.

Reference: [OpenFaaS templates Dockerfile](https://github.com/openfaas/templates/blob/4fd2802d694c3bc198aaa50f0b38d0e16e293501/template/go/Dockerfile#L42C1-L42C39)

Please let me know if there's anything else I can help you with!

**Comment by alexellis** [comment]
The warning in the Go template is very clear, do not use it. It's deprecated.

Use golang-middleware.

Please also don't delete the issue template, but include all the details requested - these are key for asynchronous communication, even if you don't think they're meaningful.

https://raw.githubusercontent.com/openfaas/templates/master/.github/ISSUE_TEMPLATE.md
