### ISSUE TITLE
Run dep init as part of the build for go and go-armhf

### ISSUE THREAD

**Issue by ericstoekl** [openfaas/templates#31]
## Expected Behaviour

Other templates like Node and Python don't make you install the dependencies yourself -- the Docker Build will take care of dependencies as part of the `faas-cli build` process. However, for `go` and `go-armhf` you are required to run `dep init` before building, or else your dependencies won't be picked up.

## Current Behaviour

You are required to run `dep init` for `go` and `go-armhf`.

## Possible Solution

Include `dep init` as part of the Dockerfile for `go`.

https://github.com/ericstoekl/templates/commit/62c12af4ae7ac352e7e6b04cc740dd7931142a52

## Steps to Reproduce (for bugs)

1. `faas-cli new --lang go gotest; faas-cli new --lang node nodetest`
2. `vim gotest/handler.go`, Include a dependency in the `import` section
3. `cd nodetest`, include a dependency with `npm install <dep> --save`, then delete `node_modeuls` and `package-lock.json`
4. `faas-cli build` each function -- `nodetest` will work and `gotest` will fail to build

## Context

Ran into this when building go functions

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
18.05.0-ce
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
swarm
* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 16
* Link to your project or a code example to reproduce issue:
https://github.com/ericstoekl/go-functions/

**Comment by alexellis** [comment]
Eric, I agree with Keiran. This is how the Go community works and vendoring is important for repeatable builds. Node and Python operate differently from Go due to differences in package management. 

https://hackernoon.com/using-go-dep-as-a-project-maintainer-641d1f3006d7

What problem are you trying to solve here?

**Comment by stefanprodan** [comment]
Running `dep init` at build time is error prone since you have no control on the dependencies versions. Having the vendor checked in is the only way to ensure that. [Vgo](https://github.com/golang/go/wiki/vgo) will solve this problem probably in go 2.0

**Comment by ericstoekl** [comment]
Makes sense, thanks for explaining. I'll close this issue.

**Comment by alexellis** [comment]
Thanks for striving to make our project better.
