### ISSUE TITLE
Kotlin Templates

### ISSUE THREAD

**Issue by napperley** [openfaas/templates#32]
In OpenFaas templates there isn't a template for Kotlin Native. A [recommendation](https://github.com/openfaas/faas/issues/709#issuecomment-394418707) was made by @iyovcheva to have Kotlin Native supported via a custom template.

## Possible Solution

The prudent course of action would be to create a custom OpenFaaS template that is based on the unofficial [Swift OpenFaas template](https://github.com/affix/openfaas-swift-template). I already have a initial implementation of the [Kotlin Native OpenFaaS template](https://gitlab.com/napperley/openfaas-kotlin-templates/tree/master/template/kotlin-native-linux-amd64) (hasn't been tested yet).

## Context

By having a template for Kotlin Native it would speed up the process of creating a Kotlin Native project that can be executed by OpenFaaS, which is less error prone.

**Comment by napperley** [comment]
Kotlin Native programs can now run on OpenFaaS :tada: .

![kotlin native on openfaas](https://user-images.githubusercontent.com/3538279/41198397-41a8f4ce-6cce-11e8-91b3-408927c34ae7.png)

**Comment by alexellis** [comment]
This is very cool. Thank you :) we need to get a quick look at the template then to list it in the faas-cli readme along with the other community templates

**Comment by napperley** [comment]
Can find the Kotlin Native template here: https://gitlab.com/napperley/openfaas-kotlin-native-template

**Comment by alexellis** [comment]
@napperley can you join the Slack community too? It would be great to chat with you there and get you connected into the project. https://docs.openfaas.com/community

I think technically we can pull from GitLab, but I wondered how you felt about having this hosted on GitHub for consistency?

The main feedback I'd give on the template is that it should ideally follow the same format as Node/Go/Python etc:

template/
template/main.x
template/function
template/function/handler.x

^ The user only sees the files in the function folder after doing `--lang x fn-name`

```
./fn-name.yml
./handler/
./handler/hander.x
```

main.x is abstracted away and remains in the template folder, but the user never sees it.

Can you take a look at the other examples and see if it's possible to follow suit?

**Comment by napperley** [comment]
@alexellis - I have created a [secondary repository](https://github.com/napperley/openfaas-kotlin-native-template) for the Kotlin Native template, and used a [Git multi push setup](https://stackoverflow.com/questions/14290113/git-pushing-code-to-two-remotes) (incl a Git **pushall** alias) to sync between the two repositories.

**Comment by napperley** [comment]
Have updated the template structure to fit in with OpenFaaS template requirements.

**Comment by alexellis** [comment]
@napperley I'd like to look at this with you it may take me a few days to get around to it. Can you try creating one or two sample functions to show how it works too?

**Comment by napperley** [comment]
There is a basic [Weather sample](https://gitlab.com/napperley/openfaas-weather-sample) available. Do note that it is incomplete since the sample doesn't have a *Dockerfile* for instance.

**Comment by napperley** [comment]
@alexellis - Just had a thought on the Kotlin templates. Would make much more sense to structure the template to include [Kotlin Native target platforms](https://kotlinlang.org/docs/reference/native-overview.html#target-platforms), eg:

```
template/
├── kotlin-js
├── kotlin-jvm
├── kotlin-native-amd64
├── kotlin-native-linux-arm32
├── kotlin-native-linux-mips
├── kotlin-native-linux-mipslittle
├── kotlin-native-wasm32
└── kotlin-native-win-amd64
```

Also the template structure would include [Kotlin JVM](https://kotlinlang.org/docs/reference/server-overview.html) and [Kotlin JS](https://kotlinlang.org/docs/reference/js-overview.html).

**Comment by alexellis** [comment]
Regular PC architecture and armv7 (armhf) are what we'd expect coverage for with armhf being optional.

**Comment by alexellis** [comment]
They have to be structured in a known format in order for the templates to be loaded and parsed. You can still have multiple named templates per repo. Like Richard suggests, you should study the official templates repo and copy the approach.

**Comment by napperley** [comment]
This issue is now resolved with a [Kotlin Native template](https://github.com/napperley/openfaas-kotlin-templates/tree/master/template/kotlin-native-linux-amd64) already available, and the [Kotlin JVM template](https://github.com/napperley/openfaas-kotlin-templates/tree/kotlin-jvm/template/kotlin-jvm) is close to being released.
