### ISSUE TITLE
Add Java template

### ISSUE THREAD

**Issue by alexellis** [openfaas/templates#38]
## Outcomes

As a user I can create a Java function using the CLI and an official template

Example:

CLI usage:

```
$ faas-cli new --lang java hello-java
```

Handler.java

Should mimic or be similar to [Lambda Java signature](https://docs.aws.amazon.com/toolkit-for-eclipse/v1/user-guide/lambda-tutorial.html):

Here is the exact AWS example:

```java
package com.example.lambda.demo;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;

public class Hello implements RequestHandler<Object, String> {

    @Override
    public String handleRequest(Object input, Context context) {
        context.getLogger().log("Input: " + input);

        // TODO: implement your handler
        return "Hello from Lambda";
    }

}
```

Ours should be similar, but with our own classes/interfaces.

## Constraints

* Must not expose user to the entrypoint or web-server needed by of-watchdog HTTP mode.

* Must allow gradle build to run as part of build

* Must allow for tests to be run in build

## Design/UX

* Build system

Should use gradle

* JDK version

Should use official OpenJDK image either v8 or v9. Perhaps this should be part of the template name such as: `java@jdk9` instead of just `java`.

As an example see C# HTTP template - https://github.com/BurtonR/csharp-kestrel-template

**Comment by affix** [comment]
I'm on it :)

**Comment by affix** [comment]
Derek assign: me

**Comment by SergeC** [comment]
JDK 9 is outdated since April. Use 8 and 10 for now, on September use v8 and v11(both are LTS).

**Comment by alexellis** [comment]
Hi @SergeC I'm working on this now and gave a demo in the community call. If you'd like to know more and be an early tester please join Slack and email alex@openfaas.com

Alex

**Comment by alexellis** [comment]
To be fair it looks like all LTS support is stopped in version 11.

http://www.oracle.com/technetwork/java/javase/eol-135779.html

This is going to use OpenJDK instead of Oracle Java, I don't know if that's relevant to discussion?

![screen shot 2018-07-05 at 4 23 46 pm](https://user-images.githubusercontent.com/6358735/42332412-ce94bad0-806f-11e8-8a0e-62e7fe9c9d6d.png)

**Comment by alexellis** [comment]
Merged.
