### ISSUE TITLE
Wrong flag set for group in non-root users

### ISSUE THREAD

**Issue by alexellis** [openfaas/templates#41]
This line in the Node template is incorrect according to the man/help page for busybox:

```
RUN addgroup -S app && adduser -S -g app app
```

`-g` must be `G`

```
/ # adduser
BusyBox v1.27.2 (2017-12-12 10:41:50 GMT) multi-call binary.

Usage: adduser [OPTIONS] USER [GROUP]

Create new user, or add USER to GROUP

        -h DIR          Home directory
        -g GECOS        GECOS field
        -s SHELL        Login shell
        -G GRP          Group
        -S              Create a system user
        -D              Don't assign a password
        -H              Don't create home directory
        -u UID          User id
        -k SKEL         Skeleton directory (/etc/skel)
```

Impact is unknown but should be fixed as soon as possible.

## Expected Behaviour

app should belong to app group

## Current Behaviour

app doesn't belong to the group

## Possible Solution

Fix flag in all/any templates including ARM.

This will need testing too.

**Comment by alexellis** [comment]
(I've updated the node template)

**Comment by ivanayov** [comment]
C# template is setting the group properly
