### ISSUE TITLE
PHP template

### ISSUE THREAD

**Issue by SergeC** [openfaas/templates#56]
PHP template request

## Expected Behaviour
Be able to deploy and run PHP functions

## Current Behaviour
Missing a template for PHP applications

## Possible Solution
Add PHP template

**Comment by alexellis** [comment]
Hi there and thank you for your interest in OpenFaaS.

The community have provided third party support for PHP. Please see the faas-cli readme file for more details.

Thanks,

Alex

**Comment by alexellis** [comment]
https://github.com/itscaro/openfaas-template-php/
