### ISSUE TITLE
Template pulled but new project generates empty folder

### ISSUE THREAD

**Issue by AnEmortalKid** [openfaas/templates#61]
I'm working on creating a custom template for scala (in a personal repository). When I pull the template, everything is fine. When I try to build with the template I get an empty directory.

Template in question: https://github.com/AnEmortalKid/scala-template-faas

Here's the structure of my repo:

```
template/
  scala/
    src/main/scala/Main.scala
    Dockerfile
    template.yml
    build.bst
    project
```

When I pull the template, I see the structure copied into my local `template` folder:

```
scala $ pwd
/MY_USER/template/scala
MY_USER scala $ ls
Dockerfile	build.sbt	project		src		template.yml
```

## Expected Behaviour
When I run `faas-cli new my-func --lang scala` I should get:

```
my-func.yml
my-func/
  src/main/scala/Main.scala
  Dockerfile
  build.sbt
  project
```

## Current Behaviour
I only get:
```
my-func.yml
my-func/
```

## Possible Solution
Maybe a pointer to some doc on what I'm doing wrong! I've looked at https://github.com/itscaro/openfaas-template-php/tree/master/template and seem to have the same structure.

## Steps to Reproduce (for bugs)

Template in question: https://github.com/AnEmortalKid/scala-template-faas

1. `faas-cli template pul https://github.com/AnEmortalKid/scala-template-faas`
2. `faas-cli new my-func --lang scala`
3. Note that `my-func` is empty
4. Note that `template/scala/` has stuff within it.

## Your Environment
* Docker version `docker version` (e.g. Docker 17.0.05 ):
```
docker -v
Docker version 18.06.0-ce, build 0ffa825
```

```
faas-cli version
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  8bd16510bc6476edbe6ab593786feefbe2fb8f6f
 version: 0.6.16

Gateway
 uri:     http://127.0.0.1:8080
 version: 0.8.9
 sha:     8f0d2d1fd6c5e3c9d2e0a73d6d256c4e232b3737
 commit:  Expose scale-function endpoint


Provider
 name:          faas-swarm
 orchestration: swarm
 version:       0.4.0 
 sha:           cd4ff365c29d6c6a49e0a75dfa98899e09c98318
```

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Mac OS X

* Link to your project or a code example to reproduce issue:
https://github.com/AnEmortalKid/scala-template-faas

**Comment by ivanayov** [comment]
Hi @AnEmortalKid 

 `my-func/` will contain all resources that are put in a `function/` folder, so you should create it and move them there.

You don't need to move to `function/` any files required for building the template , f.e. `Dockerfile`, etc., but only the code template. 

You should also add a `template.yml` file.

See the [templates repo](https://github.com/openfaas/templates/tree/master/template) for reference.

**Comment by ivanayov** [comment]
Derek add label: question

**Comment by ivanayov** [comment]
Derek add label: support

**Comment by AnEmortalKid** [comment]
@ivanayov thanks! I didn't think the `function/` folder was a thing that was required.

I have a fork with a note about that: https://github.com/AnEmortalKid/faas-cli/blob/93c5a8c0095480fc69c267df05c5c8c5be7005a9/guide/TEMPLATE.md#resources

I'll PR that in if that's a good thing to have. (I gotta setup the signer stuff to sign my commits).

**Comment by AnEmortalKid** [comment]
Closing as this solved my question.
