### ISSUE TITLE
Update Golang to 1.10

### ISSUE THREAD

**Issue by alexellis** [openfaas/templates#67]
Golang 1.11 is shown as the latest stable Golang version, but there are some issues around needing CGO and GCC which means we should not move (yet). See issue on openfaas/faas - https://github.com/openfaas/faas/issues/875

https://golang.org/dl/

If we have an official Docker image from the Docker Hub then let's try updating and test that.

Alex

**Comment by alexellis** [comment]
Derek add label: skill/beginner

**Comment by rgee0** [comment]
Derek close: Go Template now shows `FROM golang:1.10.4-alpine3.8 as builder`
