### ISSUE TITLE
Ruby isn't running as non-root

### ISSUE THREAD

**Issue by alexellis** [openfaas/templates#68]
## Expected Behaviour / Current Behaviour

The Ruby template should be running as a non-root user but I can't see the final `USER` statement in the Dockerfile.

## Possible Solution

Update the `Dockerfile` and do testing with accessing custom gems.

## Steps to Reproduce (for bugs)

1. Clone the templates repo and edit `ruby/Dockerfile`
2. `faas-cli new --lang ruby ruby-test`
2. Build / deploy / test
3. Add a gem that is consumed in the code
4. Repeat above

**Comment by ivanayov** [comment]
Derek assign: me
