### ISSUE TITLE
Install curl what already exists

### ISSUE THREAD

**Issue by fpommerening** [openfaas/templates#73]
## Expected Behaviour
The Dockerfile in the csharp template contains only required steps.

## Current Behaviour
The Dockerfile install curl to download the watchdog. After that curl will be uninstalled. There is no need for this steps. The program curl is already part on the image microsoft/dotnet:2.1-runtime.

### Console output of my test
root@vmd24929:~# docker run -it --rm microsoft/dotnet:2.1-runtime /bin/bash
root@40ce644ee8a3:/# apt-get install curl ca-certificates
Reading package lists... Done
Building dependency tree
Reading state information... Done
curl is already the newest version (7.52.1-5+deb9u7).
ca-certificates is already the newest version (20161130+nmu1+deb9u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

## Possible Solution
Remove the steps in the dockerfile.

**Comment by alexellis** [comment]
@fpommerening do you want to create a PR for this?

**Comment by alexellis** [comment]
Fixed by removing the download step and using a multi-stage build with Alpine pulling the binary.
