### ISSUE TITLE
Additional tweaks to php7 template docs

### ISSUE THREAD

**Issue by johnmccabe** [openfaas/templates#80]
## Expected Behaviour
As discussed with @alexellis, some additional tweaks to the `php7` template before the upcoming talks.

## Current Behaviour

n/a

## Possible Solution

n/a

## Steps to Reproduce (for bugs)

n/a

## Context

Some cosmetic changes to the docs for consistency.

## Your Environment

n/a

**Comment by alexellis** [comment]
Thanks for this John
